# Generated by Django 4.2.16 on 2026-06-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_data',
            field=models.TextField(blank=True, default='', verbose_name='Изображение (base64)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='photo_data',
            field=models.TextField(blank=True, default='', verbose_name='Фото (base64)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo_data',
            field=models.TextField(blank=True, default='', verbose_name='Фото (base64)'),
        ),
    ]
